
name: akilli_durak
description: Akıllı durak mobil uygulaması
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.5.0
  geolocator: ^11.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/stops.json
